#!name=彩云天气 VIP & 去广告

[filter_local]
# 禁用数据/日志上传
host, gather.colorfulclouds.net, reject

[rewrite_local]
# 广告净化/弹窗AD/去除亲友卡/去除悬浮模块
^https?:\/\/(ad|biz|wrapper|starplucker)\.cyapi\.cn\/.+\/((activity\?app_name|operation|config|req\?app_name=weather)|v\d\/(trial_card\/info|entries|friend_cards|token\/device)) url script-response-body https://raw.githubusercontent.com/edcjason/QuantumultX/main/caiyuntianqi.js

# VIP信息修改
^https?:\/\/(biz|wrapper|starplucker)\.cyapi\.cn\/(v\d\/user\?app_name|.+\/v\d\/(vip_info|user_detail)) url script-response-body https://raw.githubusercontent.com/edcjason/QuantumultX/main/caiyuntianqi.js

# SVIP地图/48小时预报（修改请求头）
^https?:\/\/(api|wrapper)\.cyapi\.cn\/v\d\/(satellite|nafp\/origin_images) url script-request-header https://raw.githubusercontent.com/edcjason/QuantumultX/main/caiyuntianqi.js

[mitm]
hostname = *.cyapi.cn
