#!name=Flightradar24 解锁

[rewrite_local]
^https://mobile\.flightradar24\.com/mobile/(user-session|subscribe|payment/check) url script-response-body https://raw.githubusercontent.com/edcjason/QuantumultX/main/Flightradar24.VIP.js

[mitm]
hostname = %APPEND% mobile.flightradar24.com
