#!name=Flightradar24 会员解锁 ddgksf2013

[rewrite_local]
^https?:\/\/mobile\.flightradar24\.com\/mobile\/(user-session|\w{9}) url script-echo-response https://raw.githubusercontent.com/edcjason/QuantumultX/main/Flightradar24.VIP.js

[mitm]
hostname = mobile.flightradar24.com
