#!name=灵敢足迹 会员解锁

[rewrite_local]
^https:\/\/footprint-api\.quthing\.com\/vip\/state url script-response-body https://raw.githubusercontent.com/edcjason/QuantumultX/main/lgzj.js

[mitm]
hostname = footprint-api.quthing.com
