[General]
loglevel = notify
dns-server = system, 119.29.29.29, 223.5.5.5

[Proxy]
DIRECT = direct
REJECT = reject

[Proxy Group]
节点选择 = select, DIRECT
自动选择 = url-test, DIRECT, interval=600, tolerance=100
国外媒体 = select, 节点选择, DIRECT
国内媒体 = select, DIRECT, 节点选择
微软服务 = select, DIRECT, 节点选择
苹果服务 = select, DIRECT, 节点选择
Telegram = select, 节点选择, DIRECT
Final = select, 节点选择, DIRECT

404: Not Found