[General]
loglevel = notify
dns-server = system, 119.29.29.29, 223.5.5.5

[Proxy]
DIRECT = direct
REJECT = reject

[Proxy Group]
节点选择 = select, DIRECT
自动选择 = url-test, DIRECT, interval=600, tolerance=100
国外媒体 = select, 节点选择, DIRECT
国内媒体 = select, DIRECT, 节点选择
微软服务 = select, DIRECT, 节点选择
苹果服务 = select, DIRECT, 节点选择
Telegram = select, 节点选择, DIRECT
Final = select, 节点选择, DIRECT

[Rule]
DOMAIN, ad.12306.cn, direct
DOMAIN, sdkapp.uve.weibo.com, direct
DOMAIN-SUFFIX, ddgksf2013.top, proxy
IP-CIDR, 10.0.0.0/8, direct
IP-CIDR, 127.0.0.0/8, direct
IP-CIDR, 172.16.0.0/12, direct
IP-CIDR, 192.168.0.0/16, direct
IP-CIDR, 224.0.0.0/24, direct
IP-CIDR, 182.254.116.0/24, direct
GEOIP, cn, direct
FINAL, 兜底分流
