#!name=PikPak区域解锁 edcwork

[rewrite_local]
^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt$ url script-response-body https://raw.githubusercontent.com/edcjason/QuantumultX/main/Pikpak.js

[mitm]
hostname = buy.itunes.apple.com
