#!name=PikPak区域解锁 edcwork

[rewrite_local]
^https:\/\/api-drive\.mypikpak\.com\/(vip\/v\d\/(vip\/info|allSubscriptionStatus)|drive\/v\d\/about\?space) url script-response-body https://raw.githubusercontent.com/edcjason/QuantumultX/main/PikPak.js

[mitm]
hostname = api-drive.mypikpak.com
